/**
 * The homepage (/) — "The Command Core". Every word on the page lives here.
 *
 * Home.tsx and its crash fallback HomeFallback.tsx both read from this file,
 * so the two can never drift. Edit copy here, not in the components.
 *
 * The proof on this page (the company names, the talks, the Parliament
 * presentation, the capacity range and the benchmarks) was supplied by Phila
 * on 24 September 2026 for publication. The before/after figures are shown as
 * illustrative benchmarks and must keep that label next to them.
 *
 * 29 September 2026: the Command Core is private AI. Open-weight models run
 * on equipment we choose, deploy and look after, set up around the client's
 * business. The pitch is "Let us help you own your intelligence." Phila's
 * rules for this page: sell the outcome, not the parts (no hardware or model
 * names; the details come in the proposal), and it is application only. The
 * only deployment so far is GrowthCred's own, so no client is ever described
 * as running one. The logos and stories come from training and builds, and
 * are labelled that way.
 */

/** Where every "Apply" goes. The call is earned through an application. */
export const APPLY_HREF = "/call";

export const HERO = {
  /** One static, prerendered <h1>: "Let us help you own your intelligence.",
   *  Phila's exact pitch (29 Sep 2026), with the ownership marked like a
   *  marker pen. The admin problem it solves moves into the sub. */
  headlineLead: "Let us help you",
  headlineMark: "own your intelligence.",
  /** The quieter second way in, beside the Apply button. */
  secondary: { label: "Read client stories", to: "/stories" },
  sub: "Your own AI. On equipment we choose and set up for you. Built around how your business works. It takes the admin that eats 20–\u206040% of your week. No per-seat subscriptions. Your data never leaves the building.",
  cta: "Apply to Work With Us",
  scarcity: "Engagements are limited. Not every application is accepted.",
} as const;

/* The proof strip is the client logos: src/components/ClientLogos.tsx,
   generated by scripts/make-logos.py from content/client-logos/. They trained
   or built with us; none of them is described as running private AI. */
export const LOGOS_LABEL = "Organisations we've worked with";

export const PROOF_LINE =
  "7 AI talks at WeWork Johannesburg. AI system presented at Parliament, Cape Town.";

export const CAPACITY = {
  heading: "That 20–40% isn't just admin. It's your most expensive hours.",
  gap: "Your decisions are worth R20,000 an hour. Admin is R200-an-hour work. When you do both, the business pays the gap.",
  lead: "For a R20M–R100M firm, that gap costs",
  figure: "R3M–R10M",
  tail: "a year.",
  /** Sits under the R200 vs R20,000 comparison. */
  tried: "Hiring didn't fix it. New tools didn't either. Both still need you to check the work.",
  closeA: "The fix is not more people.",
  closeB: "It's building your judgment into the business.",
  /** The two hourly figures the comparison bar is drawn from. */
  lowRate: 200,
  highRate: 20000,
};

/* ---------------- Renting AI, and owning it ---------------- */

export const RENTING = {
  eyebrow: "The rented way",
  heading: "Renting AI doesn't fix it either.",
  lead: "Most firms rent their AI. A seat for every person. Every month. So what are you actually paying for?",
  items: [
    {
      t: "The bill grows with your team.",
      b: "Every new hire is another seat. What does one seat cost you a month? Now times your headcount. Every month. For as long as you use it.",
    },
    {
      t: "Your documents leave the building.",
      b: "Client files, contracts and numbers go to someone else's servers to be processed. Under POPIA, what happens to them is still on you.",
    },
    {
      t: "It doesn't know your business.",
      b: "A rented tool starts every task from zero. So your people spend the time it saved explaining your business to it.",
    },
  ],
  close: "You're paying rent on something you use every day. At some point you buy the house.",
};

export const OWN = {
  eyebrow: "The Command Core",
  heading: "Your own intelligence. Owned, not rented.",
  lead: "We handle the equipment. You never have to think about it. We choose what fits your business, set it up and look after it.",
  items: [
    {
      t: "Equipment that fits you",
      b: "Sized to your team and your work. We deploy it and we keep it running. You don't need to know what's inside.",
    },
    {
      t: "An AI that knows your business",
      b: "Set up on your documents, your templates and the way you write. It starts every task already knowing you.",
    },
    {
      t: "Agents built for your work",
      b: "Custom agents for the jobs that eat your week. Proposals. Client enquiries. Answers to questions. SOPs.",
    },
    {
      t: "Your team, trained",
      b: "We train your people on it, on their own work. So it gets used on Monday. Not admired on Friday.",
    },
  ],
  honest: "Is it magic? No. It's excellent at documents, questions and the admin in between. Before you sign, we tell you straight what it will and won't do for you.",
  owned: "No per-seat subscriptions. Your data stays in the building. And it's yours.",
  more: { to: "/private-ai", label: "Why own it? The full case" },
};

/** Before/after. `from`/`to` are the same quantity in one unit, for the bars. */
export type Benchmark = {
  metric: string;
  before: string;
  after: string;
  from: number;
  to: number;
};

export const BEFORE_AFTER = {
  eyebrow: "Before / After",
  heading: "What changes when the work stops waiting for you.",
  rows: [
    { metric: "Owner hours per week", before: "65", after: "35", from: 65, to: 35 },
    { metric: "Proposal turnaround", before: "3 days", after: "3 hrs", from: 72, to: 3 },
    { metric: "Lead follow-up", before: "48 hrs", after: "4 min", from: 48 * 60, to: 4 },
    { metric: "Deals lost to slow response", before: "20%", after: "2%", from: 20, to: 2 },
  ] satisfies Benchmark[],
  /** Must stay beside the figures wherever they render. */
  disclaimer: "Illustrative benchmarks. Results vary by engagement.",
};

export type Stage = { band: string; family: string; name: string; line: string };

export const STAGES = {
  eyebrow: "Engagements",
  heading: "Pick your stage.",
  sub: "Same method. The scope grows with the business.",
  /** Every stage is the Command Core, so every stage is the client's own AI. */
  equipment: "Every stage runs on your own AI, on equipment we choose and deploy to fit you.",
  items: [
    {
      band: "R5M–R50M",
      family: "Command Core",
      name: "Velocity",
      line: "One day. Your biggest admin drains fixed before you leave the room.",
    },
    {
      band: "R50M–R200M",
      family: "Command Core",
      name: "Integration",
      line: "90 days. The same fix built into sales, delivery and admin.",
    },
    {
      band: "R200M+",
      family: "Command Core",
      name: "Transformation",
      line: "Your whole operating model rebuilt, department by department. Custom scope.",
    },
  ] satisfies Stage[],
};

export const METHOD = {
  eyebrow: "The Method",
  heading: "How you get the 20–40% back.",
  steps: [
    {
      t: "Audit",
      b: "Find where your week goes. Put a rand value on every hour stuck on your desk.",
    },
    {
      t: "Deploy",
      b: "Set up your own AI on equipment that fits you. Build it around the way you work. First result in 14 days.",
    },
    {
      t: "Embed",
      b: "Keep it sharp. Better models go in as they come out. Hours back tracked every month.",
    },
  ],
};

export const FOUNDER = {
  name: "Phila Ngwenya",
  title: "Founder, GrowthCred",
  /** The bio, one line per credential, in the order Phila wrote it. */
  credentials: [
    "Runs GrowthCred on its own private AI.",
    "Runs his own companies on the same systems he builds for clients.",
    "Co-developed an AI system presented at Parliament, Cape Town.",
    "7 AI talks at WeWork Johannesburg.",
    "Rosebank, South Africa.",
  ],
};

export const GUARANTEE = {
  lead: "20% of your week back.",
  accent: "Or you don't pay.",
  body: "If the Command Core doesn't give you back at least 20% of your week, the engagement is on us.",
};

export const CLOSE = {
  heading: "Next week, that 20–40% goes again.",
  sub: "Unless something changes. Apply and we'll tell you if it's a fit.",
  cta: "Apply",
};

/* ---------------- Stories: the proof behind the claims ---------------- */

export type HomeStory = {
  href: string;
  client: string;
  /** What the business does, as a short label. */
  sector: string;
  headline: string;
  body: string;
  image?: { src: string; alt: string; width: number; height: number };
  /** The client's own words, verbatim. */
  quote?: string;
  /** A before/after the client reported. */
  stat?: { before: string; after: string };
};

export const STORIES = {
  eyebrow: "Client stories",
  heading: "This isn't theory.",
  sub: "These are owners who worked with us through our training and builds. Same method. Different industries.",
  all: "Read all client stories",
  items: [
    {
      href: "/stories/mne-waste",
      client: "MNE Waste",
      sector: "Waste management",
      headline: "An Operator's Brain, built in one day.",
      body: "Sandile runs trucks, drivers, compliance and municipal contracts. He built his Operator's Brain at the first Operator Intensive and is now fully operational.",
      image: {
        src: "/images/stories/operators-intensive-session.jpg",
        alt: "Owners working through the first Operator Intensive at WeWork Rosebank",
        width: 1200,
        height: 900,
      },
    },
    {
      href: "/stories/demure-international",
      client: "Demure International",
      sector: "Beauty & cosmetics",
      headline: "A sharper AI after one session.",
      quote: "My Claude has been operating a lot better since the last session.",
      body: "Macaela Oor runs orders, inventory, client bookings and brand content for Enigma Essentials.",
    },
    {
      href: "/stories",
      client: "TaiAscend",
      sector: "Client result",
      headline: "A three-day document, done in two hours.",
      stat: { before: "3 days", after: "2 hrs" },
      body: "A document process that took three days now takes two hours.",
    },
    {
      href: "/stories/operators-intensive-wework-rosebank",
      client: "Operator Intensive",
      sector: "WeWork Rosebank",
      headline: "Five seats. Sold out.",
      body: "Owners whose businesses depended entirely on them walked out with working systems.",
      image: {
        src: "/images/stories/operators-intensive-sold-out.jpg",
        alt: "GrowthCred announcement: Your week is sold out",
        width: 390,
        height: 330,
      },
    },
  ] satisfies HomeStory[],
};

/* ---------------- Other ways in (and the rest of the site) ---------------- */

export const WAYS = {
  eyebrow: "Other ways in",
  heading: "Not ready for an engagement? Start smaller.",
  sub: "Every route below uses the same method, at a smaller scale.",
  items: [
    {
      href: "/corporate-ai-training",
      title: "Corporate AI training",
      line: "Train every team to produce its reports and documents faster. Priced per employee.",
    },
    {
      href: "/ai-automation-south-africa",
      title: "AI automation, done for you",
      line: "We identify your repetitive work and build AI-assisted workflows around it, with your team.",
    },
    {
      href: "/ai-training-south-africa",
      title: "AI training for owners",
      line: "Learn to use AI on the work your business already does: proposals, research, follow-ups and admin.",
    },
    {
      href: "/workshop",
      title: "The one-day online workshop",
      line: "Build your first systems yourself, guided, in one day. Bring a laptop and real work.",
    },
    {
      href: "/webinar",
      title: "The free online class",
      line: "A practical first hour on giving AI the context your business needs.",
    },
  ],
};

export const GUIDES = {
  eyebrow: "The field guide",
  heading: "Articles for owners who want AI to do real work.",
  all: "Browse every guide",
};

/* ---------------- FAQ ---------------- */

export const FAQ: { q: string; a: string }[] = [
  {
    q: "What is the Command Core?",
    a: "Your own AI, on equipment we choose, deploy and look after for you. It's set up around how your business works, with agents built for your admin. So the work eating 20–40% of your week stops landing on your desk. You own it. You don't rent it.",
  },
  {
    q: "Where does our data go?",
    a: "It stays with you. Your AI runs on your own equipment, so your documents aren't sent to an outside AI company to be processed. Before anything goes in, we agree in writing who can reach the system, and how.",
  },
  {
    q: "What equipment do we need?",
    a: "You don't buy anything yourself. We choose the equipment that fits your team and your work. We deploy it and we look after it. The details come in your proposal.",
  },
  {
    q: "What happens when a better AI model comes out?",
    a: "We test it on your work. If it does the job better, we put it in. Your setup, your documents and your agents stay. You don't start again.",
  },
  {
    q: "Who is it for?",
    a: "Owner-led businesses where you, the founder, are the bottleneck. From R5M to over R200M in revenue. Pick your stage above. The engagement grows with your business.",
  },
  {
    q: "How is this different from ChatGPT?",
    a: "ChatGPT is rented, general and outside your building. It knows nothing about your business, so its answers could be for anyone. Your Command Core runs on your own equipment. It starts every task already knowing how you work. Will it beat the newest ChatGPT at everything? No. At your documents, your enquiries and your SOPs, that's what it's built for.",
  },
  {
    q: "Does it work in my industry?",
    a: "We've worked with owners in waste management and in beauty and cosmetics. Your AI is set up on your knowledge, not a template. So your industry changes. The method doesn't.",
  },
  {
    q: "How is it different from the one-day workshop?",
    a: "The workshop is one day, online. You build your first systems yourself, on tools you rent. The Command Core is an engagement. We deploy your own AI on your own equipment and build it into your departments.",
  },
  {
    q: "What does it cost?",
    a: "It depends on your stage and your scope. Transformation engagements are scoped to you. Engagements are limited, so apply and we'll tell you if it's a fit.",
  },
  {
    q: "Where is GrowthCred based?",
    a: "Rosebank, Johannesburg, South Africa. I run GrowthCred from here myself.",
  },
];
