/**
 * The homepage (/) — "The Command Core". Every word on the page lives here.
 *
 * Home.tsx and its crash fallback HomeFallback.tsx both read from this file,
 * so the two can never drift. Edit copy here, not in the components.
 *
 * The proof on this page (the company names, the talks, the Parliament
 * presentation, the capacity range and the benchmarks) was supplied by Phila
 * on 24 September 2026 for publication. The before/after figures are shown as
 * illustrative benchmarks and must keep that label next to them.
 */

/** Where every "Apply" goes. The call is earned through an application. */
export const APPLY_HREF = "/call";

export const HERO = {
  /** One static, prerendered <h1>: "20–40% of your time lost to admin. Gone.",
   *  with the two marked phrases highlighted like a marker pen. Phila's
   *  rewrite (26 Sep 2026) of "time drain", so the problem is named in plain
   *  words the moment the page opens. */
  headlineLead: "20–40% of your time",
  headlineMark: "lost to admin.",
  headlineAccent: "Gone.",
  /** The quieter second way in, beside the Apply button. */
  secondary: { label: "Read client stories", to: "/stories" },
  sub: "Proposals. Follow-ups. Approvals. The work that waits on your desk. The Command Core takes it off, so the business keeps moving without you in the room.",
  cta: "Apply to Work With Us",
  scarcity: "Engagements are limited. Not every application is accepted.",
} as const;

/* The proof strip is the client logos: src/components/ClientLogos.tsx,
   generated by scripts/make-logos.py from content/client-logos/. */

export const PROOF_LINE =
  "7 AI talks at WeWork Johannesburg. AI system presented at Parliament, Cape Town.";

export const CAPACITY = {
  heading: "That 20–40% isn't just admin. It's your most expensive hours.",
  gap: "Your decisions are worth R20,000 an hour. Admin is R200-an-hour work. When you do both, the business pays the gap.",
  lead: "For a R20M–R100M firm, that gap costs",
  figure: "R3M–R10M",
  tail: "a year.",
  /** Sits under the R200 vs R20,000 comparison. */
  tried: "Hiring didn't fix it. New tools didn't either. Both still need you to check the work.",
  closeA: "The fix is not more people.",
  closeB: "It's building your judgment into the business.",
  /** The two hourly figures the comparison bar is drawn from. */
  lowRate: 200,
  highRate: 20000,
};

/** Before/after. `from`/`to` are the same quantity in one unit, for the bars. */
export type Benchmark = {
  metric: string;
  before: string;
  after: string;
  from: number;
  to: number;
};

export const BEFORE_AFTER = {
  eyebrow: "Before / After",
  heading: "What changes when the work stops waiting for you.",
  rows: [
    { metric: "Owner hours per week", before: "65", after: "35", from: 65, to: 35 },
    { metric: "Proposal turnaround", before: "3 days", after: "3 hrs", from: 72, to: 3 },
    { metric: "Lead follow-up", before: "48 hrs", after: "4 min", from: 48 * 60, to: 4 },
    { metric: "Deals lost to slow response", before: "20%", after: "2%", from: 20, to: 2 },
  ] satisfies Benchmark[],
  /** Must stay beside the figures wherever they render. */
  disclaimer: "Illustrative benchmarks. Results vary by engagement.",
};

export type Stage = { band: string; family: string; name: string; line: string };

export const STAGES = {
  eyebrow: "Engagements",
  heading: "Pick your stage.",
  sub: "Same method. The scope grows with the business.",
  items: [
    {
      band: "R5M–R50M",
      family: "Command Core",
      name: "Velocity",
      line: "One day. Your biggest admin drains fixed before you leave the room.",
    },
    {
      band: "R50M–R200M",
      family: "Command Core",
      name: "Integration",
      line: "90 days. The same fix built into sales, delivery and admin.",
    },
    {
      band: "R200M+",
      family: "Command Core",
      name: "Transformation",
      line: "Your whole operating model rebuilt, department by department. Custom scope.",
    },
  ] satisfies Stage[],
};

export const METHOD = {
  eyebrow: "The Method",
  heading: "How you get the 20–40% back.",
  steps: [
    {
      t: "Audit",
      b: "Find where your week goes. Put a rand value on every hour stuck on your desk.",
    },
    {
      t: "Deploy",
      b: "Build systems that do that work the way you would. First result in 14 days.",
    },
    {
      t: "Embed",
      b: "Keep them sharp. New capabilities every quarter. Hours back tracked every month.",
    },
  ],
};

export const FOUNDER = {
  name: "Phila Ngwenya",
  title: "Founder, GrowthCred",
  /** The bio, one line per credential, in the order Phila wrote it. */
  credentials: [
    "Runs his own companies on the same systems he builds for clients.",
    "Co-developed an AI system presented at Parliament, Cape Town.",
    "7 AI talks at WeWork Johannesburg.",
    "Rosebank, South Africa.",
  ],
};

export const GUARANTEE = {
  lead: "20% of your week back.",
  accent: "Or you don't pay.",
  body: "If the Command Core doesn't give you back at least 20% of your week, the engagement is on us.",
};

export const CLOSE = {
  heading: "Next week, that 20–40% goes again.",
  sub: "Unless something changes. Apply and we'll tell you if it's a fit.",
  cta: "Apply",
};

/* ---------------- Stories: the proof behind the claims ---------------- */

export type HomeStory = {
  href: string;
  client: string;
  /** What the business does, as a short label. */
  sector: string;
  headline: string;
  body: string;
  image?: { src: string; alt: string; width: number; height: number };
  /** The client's own words, verbatim. */
  quote?: string;
  /** A before/after the client reported. */
  stat?: { before: string; after: string };
};

export const STORIES = {
  eyebrow: "Client stories",
  heading: "This isn't theory.",
  sub: "Same method, different industries. Built from your knowledge, not a template.",
  all: "Read all client stories",
  items: [
    {
      href: "/stories/mne-waste",
      client: "MNE Waste",
      sector: "Waste management",
      headline: "An Operator's Brain, built in one day.",
      body: "Sandile runs trucks, drivers, compliance and municipal contracts. He built his Operator's Brain at the first Operator Intensive and is now fully operational.",
      image: {
        src: "/images/stories/operators-intensive-session.jpg",
        alt: "Owners working through the first Operator Intensive at WeWork Rosebank",
        width: 1200,
        height: 900,
      },
    },
    {
      href: "/stories/demure-international",
      client: "Demure International",
      sector: "Beauty & cosmetics",
      headline: "A sharper AI after one session.",
      quote: "My Claude has been operating a lot better since the last session.",
      body: "Macaela Oor runs orders, inventory, client bookings and brand content for Enigma Essentials.",
    },
    {
      href: "/stories",
      client: "TaiAscend",
      sector: "Client result",
      headline: "A three-day document, done in two hours.",
      stat: { before: "3 days", after: "2 hrs" },
      body: "A document process that took three days now takes two hours.",
    },
    {
      href: "/stories/operators-intensive-wework-rosebank",
      client: "Operator Intensive",
      sector: "WeWork Rosebank",
      headline: "Five seats. Sold out.",
      body: "Owners whose businesses depended entirely on them walked out with working systems.",
      image: {
        src: "/images/stories/operators-intensive-sold-out.jpg",
        alt: "GrowthCred announcement: Your week is sold out",
        width: 390,
        height: 330,
      },
    },
  ] satisfies HomeStory[],
};

/* ---------------- Other ways in (and the rest of the site) ---------------- */

export const WAYS = {
  eyebrow: "Other ways in",
  heading: "Not ready for an engagement? Start smaller.",
  sub: "Every route below uses the same method, at a smaller scale.",
  items: [
    {
      href: "/ai-automation-south-africa",
      title: "AI automation, done for you",
      line: "We identify your repetitive work and build AI-assisted workflows around it, with your team.",
    },
    {
      href: "/ai-training-south-africa",
      title: "AI training for owners",
      line: "Learn to use AI on the work your business already does: proposals, research, follow-ups and admin.",
    },
    {
      href: "/workshop",
      title: "The one-day online workshop",
      line: "Build your first systems yourself, guided, in one day. Bring a laptop and real work.",
    },
    {
      href: "/webinar",
      title: "The free online class",
      line: "A practical first hour on giving AI the context your business needs.",
    },
  ],
};

export const GUIDES = {
  eyebrow: "The field guide",
  heading: "Articles for owners who want AI to do real work.",
  all: "Browse every guide",
};

/* ---------------- FAQ ---------------- */

export const FAQ: { q: string; a: string }[] = [
  {
    q: "What is the Command Core?",
    a: "AI systems built from how you work, so the admin eating 20–40% of your week stops landing on your desk.",
  },
  {
    q: "Who is it for?",
    a: "Owner-led businesses where the founder is the bottleneck, from R5M to over R200M in revenue. Pick your stage above; the engagement changes with the size of the business.",
  },
  {
    q: "How is this different from using ChatGPT on its own?",
    a: "A raw AI tool knows nothing about your business, so it gives answers that could be for anyone. We build the system from your knowledge (how you run, who you serve, how you speak), so every task starts with full context.",
  },
  {
    q: "Does it work in my industry?",
    a: "MNE Waste runs trucks, drivers, compliance and municipal contracts. Demure International runs a beauty and cosmetics brand. The system is built from your knowledge, not a template, so the industry changes and the method does not.",
  },
  {
    q: "How is it different from the one-day workshop?",
    a: "The workshop is a one-day online session where you build your first systems yourself. The Command Core is an engagement: we audit, deploy and embed founder-grade operations across your departments.",
  },
  {
    q: "What does it cost?",
    a: "It depends on your stage and scope, and transformation engagements are custom-scoped. Engagements are limited: apply and we'll determine fit.",
  },
  {
    q: "Where is GrowthCred based?",
    a: "GrowthCred is founder-led from Rosebank, Johannesburg, South Africa.",
  },
];
