import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Section, Eyebrow, Button, ButtonLink, Faq } from "../components/ui";
import { registerForWebinar } from "../lib/supabase";
import { WEBINAR } from "../lib/webinar";
import { whatsappUrl } from "../lib/contact";
import { track } from "../lib/analytics";
export default function NextClass(){
  const [name,setName]=useState('');const [email,setEmail]=useState('');const [whatsapp,setWhatsapp]=useState('');
  const [state,setState]=useState<'idle'|'sending'|'done'|'error'>('idle');
  useEffect(()=>track('webinar_view'),[]);
  async function submit(e:React.FormEvent){e.preventDefault();if(state==='sending')return;setState('sending');try{
    const result=await registerForWebinar({webinar:WEBINAR.slug,name:name.trim(),email:email.trim(),whatsapp:whatsapp.trim(),source:'webinar_page'});
    if(!result.ok || result.confirmed === false){setState('error');return;}
    track('webinar_register',{webinar:WEBINAR.slug,configured:true});setState('done');
  }catch{setState('error');}}
  return <>
    <Section dark className="pt-12 md:pt-20"><div className="max-w-[850px]"><Eyebrow dark>Free online AI class · South Africa</Eyebrow><h1 className="mt-5 text-4xl text-cream md:text-6xl">Give AI the context your business needs.</h1><p className="mt-7 max-w-[60ch] text-lg text-cream/85">Join Phila Ngwenya for a practical introduction to using AI on real business work. Learn how to brief a tool with your services, customers and way of working.</p><p className="mt-5 text-cream">Online · Free · Session details confirmed on registration</p><a href="#register" className="mt-7 inline-flex min-h-12 items-center rounded-full bg-gold px-6 font-semibold text-midnight no-underline">Register for the next class ↗</a></div></Section>
    <Section><div className="grid gap-12 md:grid-cols-2"><div><h2 className="text-3xl">A useful first step.</h2><p className="mt-5 leading-relaxed">We look at repetitive admin, explain what business context does and show how to evaluate an AI draft. The class is for business owners who want a practical starting point, without needing to code.</p><ul className="mt-6 list-disc space-y-3 pl-5"><li>Choose one task worth improving.</li><li>Understand the information an AI tool needs.</li><li>Keep human review where it matters.</li><li>Decide whether the workshop is your next step.</li></ul><p className="mt-6 text-sm text-muted">This is registration for a future online class, not an instant recording. We confirm the session details with you on registration.</p><p className="mt-5"><Link to="/guides/business-brain">Start now with the free business-context guide</Link>.</p></div>
    <div id="register" className="scroll-mt-28 rounded-2xl border border-midnight/15 bg-white p-6 md:p-8">
      {state==='done'?<div role="status"><h2 className="text-2xl">Your registration is received.</h2><p className="mt-4">We’ll confirm the online session details with you using the contact information you provided.</p><p className="mt-4">You don’t need to book travel. If you need to check your registration, <a href={whatsappUrl('Hi Phila, I would like to check my registration for the next online AI class.')}>message us on WhatsApp</a>.</p><ButtonLink to="/guides/business-brain" className="mt-6">Read the starting guide</ButtonLink></div>:<><h2 className="text-2xl">Register for the next class</h2><p className="mt-3 text-sm">Free and online. Date, time and joining details confirmed on registration.</p><form onSubmit={submit} className="mt-6 grid gap-4"><label className="grid gap-2 text-sm">Name<input required maxLength={100} autoComplete="given-name" value={name} onChange={e=>setName(e.target.value)} className="min-h-12 rounded-lg border border-midnight/20 px-3 text-base"/></label><label className="grid gap-2 text-sm">Email<input type="email" required maxLength={254} autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} className="min-h-12 rounded-lg border border-midnight/20 px-3 text-base"/></label><label className="grid gap-2 text-sm">WhatsApp number<input type="tel" required maxLength={25} autoComplete="tel" value={whatsapp} onChange={e=>setWhatsapp(e.target.value)} className="min-h-12 rounded-lg border border-midnight/20 px-3 text-base"/></label><Button disabled={state==='sending'} type="submit">{state==='sending'?'Sending…':'Register for free'}</Button></form><p className="mt-4 text-xs leading-relaxed">We use these details to manage your registration. Read our <Link to="/privacy">privacy policy</Link>.</p>{state==='error'&&<p role="alert" className="mt-4 text-sm text-red-700">Your registration could not be confirmed. Please try again or <a href={whatsappUrl('Hi Phila, I would like to register for the next free online AI class.')}>register with us on WhatsApp</a>.</p>}</>}
    </div></div></Section>
    <Section className="pt-0"><h2 className="mb-8 text-3xl">Before you register.</h2><Faq items={[{q:'When and where is the class?',a:'The class is online. The date, time and joining details are confirmed on registration.'},{q:'Is the free class the same as the workshop?',a:'No. The free class is an introduction. The one-day online workshop is a separate R990 offer where you build workflows with guidance.'},{q:'Do I need to buy an AI subscription first?',a:'No purchase is needed to register for the free class. Confirm the tool requirements with us before buying a subscription for the workshop.'},{q:'Can I watch a recording immediately?',a:'This registration is for a future session. A recording is not currently offered as an instant download. You can read our free guides now.'}]}/></Section>
  </>;
}
