import LOGOS from "../content/clientLogos.json";
import { cn } from "./ui";

/**
 * The organisations GrowthCred has worked with, as one strip in the site's own
 * ink. Every logo is a midnight silhouette generated by scripts/make-logos.py
 * from the originals in content/client-logos/, sized so each carries the same
 * visual weight — eight brand colours in a row read as noise, one ink reads as
 * a single claim.
 *
 * `TYPESET` holds clients whose supplied file could not be used (Ncedo
 * Afrika's lettering is white on white); they are set as a name in the same
 * ink until a usable file arrives, rather than dropped from the proof.
 */

type Logo = (typeof LOGOS)[number];

const TYPESET = ["Ncedo Afrika"];

function Mark({ logo, eager }: { logo: Logo; eager: boolean }) {
  return (
    <img
      src={logo.src}
      alt={logo.name}
      width={Math.round((logo.width * logo.displayHeight) / logo.height)}
      height={logo.displayHeight}
      loading={eager ? "eager" : "lazy"}
      decoding="async"
      className="block max-w-none opacity-70 transition-opacity duration-300 hover:opacity-100"
    />
  );
}

function Name({ name }: { name: string }) {
  return (
    <span className="whitespace-nowrap font-display text-xl font-extrabold tracking-[-0.03em] text-midnight/70 md:text-2xl">
      {name}
    </span>
  );
}

/* The duplicate marquee group keeps its alt text: the whole group is
   aria-hidden, and the site's alt-text gate rightly rejects empty alts. */
function Items({ eager = false }: { eager?: boolean }) {
  return (
    <>
      {LOGOS.map((logo) => (
        <li key={logo.slug} className="flex shrink-0 items-center">
          <Mark logo={logo} eager={eager} />
        </li>
      ))}
      {TYPESET.map((name) => (
        <li key={name} className="flex shrink-0 items-center">
          <Name name={name} />
        </li>
      ))}
    </>
  );
}

/**
 * The scrolling proof strip used on / and /corporate-ai-training. A seamless
 * loop where motion is welcome, a static wrapped row everywhere else (the
 * .cc-marquee rules in index.css).
 */
export function ClientLogos({ className }: { className?: string }) {
  return (
    <div className={cn("cc-marquee overflow-hidden", className)}>
      <div className="cc-marquee-track">
        <ul className="cc-marquee-group" aria-label="Organisations we have worked with">
          <Items eager />
        </ul>
        <ul className="cc-marquee-group cc-marquee-dup" aria-hidden="true">
          <Items eager />
        </ul>
      </div>
    </div>
  );
}
