import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { ROUTES, ALIASES, SITE, structuredData, render } from '../dist-ssr/entry-server.js';
const template=await readFile('dist/index.html','utf8');
const escape=s=>s.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const interactive=new Set(['/checkout','/upsell','/downsell','/build','/thank-you','/brain']);
const records=[];
async function writePage(meta){
  const prerendered=!interactive.has(meta.path);
  const content=prerendered?await render(meta.path):'<noscript><p>JavaScript is needed for this interactive page. <a href="/contact">Contact GrowthCred</a> for help registering.</p></noscript>';
  const canonical=SITE+(meta.canonical??meta.path);
  const tags=`<title>${escape(meta.title)}</title>
    <meta name="description" content="${escape(meta.description)}" />
    <meta name="robots" content="${meta.index?'index, follow, max-image-preview:large':'noindex, follow'}" />
    <link rel="canonical" href="${escape(canonical)}" />
    <meta property="og:title" content="${escape(meta.title)}" />
    <meta property="og:description" content="${escape(meta.description)}" />
    <meta property="og:url" content="${escape(canonical)}" />
    <meta property="og:type" content="${meta.path.startsWith('/guides/')?'article':'website'}" />
    <meta property="og:site_name" content="GrowthCred" />
    <meta property="og:locale" content="en_ZA" />
    <meta property="og:image" content="${SITE}/images/search-share.png" />
    <meta property="og:image:width" content="1200" /><meta property="og:image:height" content="630" />
    <meta property="og:image:alt" content="GrowthCred: practical AI for South African business owners" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${escape(meta.title)}" />
    <meta name="twitter:description" content="${escape(meta.description)}" />
    <meta name="twitter:image" content="${SITE}/images/search-share.png" />
    <script id="site-schema" type="application/ld+json">${JSON.stringify(structuredData(meta)).replaceAll('<','\\u003c')}</script>`;
  const html=template.replace(/<title>[\s\S]*?<\/title>/,'').replace(/<meta name="description"[^>]*>/,'').replace('</head>',tags+'\n  </head>').replace('<div id="root"></div>',`<div id="root"${prerendered?` data-prerendered="${escape(meta.path)}"`:''}>${content}</div>`);
  const file=meta.path==='/'?'index.html':meta.path.slice(1)+'.html';
  await mkdir(path.dirname('dist/'+file),{recursive:true});await writeFile('dist/'+file,html.replace(/[ \t]+$/gm,''));
  records.push({...meta,file,prerendered});
}
for(const meta of ROUTES){if(!ALIASES[meta.path])await writePage(meta);}
await writePage({path:'/404',title:'Page Not Found | GrowthCred',description:'Find GrowthCred’s AI workshops, business guides and contact information.',index:false});
await writeFile('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${ROUTES.filter(r=>r.index&&!ALIASES[r.path]).map(r=>`\n  <url><loc>${SITE+r.path}</loc>${r.modified?`<lastmod>${r.modified}</lastmod>`:''}</url>`).join('')}\n</urlset>\n`);
const redirects=Object.entries(ALIASES).map(([from,to])=>`${from} ${to} 301`).join('\n');
await writeFile('dist/_redirects',`# Generated by scripts/prerender.mjs. cPanel uses .htaccess instead.\nhttps://www.growthcred.co.za/* https://growthcred.co.za/:splat 301!\n${redirects}\n${records.filter(r=>r.path!=='/').map(r=>`${r.path} /${r.file} 200`).join('\n')}\n/* /404.html 404\n`);
await writeFile('dist/search-manifest.json',JSON.stringify({routes:records,aliases:ALIASES},null,2)+'\n');
console.log(`Prerendered ${records.filter(r=>r.prerendered).length} complete pages; ${records.length} route documents generated.`);
